name: Daily Update Bot

on:
  schedule:
    - cron : "40 06 * * *"
  workflow_dispatch: # allows  to run it manually to test it

jobs:
  update_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get date
        run: |
          echo "Last updated on: $(date)" > ./data.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated date update"
